package CapaVista;

import CapaDomini.ControladorHidato;
import CapaDomini.ControladorPartida;
import CapaDomini.Tauler;
import CapaDomini.TaulerDisplayerCallbacks;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by daniel on 16/11/15.
 */
public class JugarPartida
{
    private TaulerDisplayer taulerDisplayer1;
    private JPanel panel1;
    private JButton guardarPartidaButton;
    private JButton sortirButton;
    private Tauler t;
    private TaulerDisplayerCallbacks callbacks;

    public JugarPartida(Tauler taulerProgres, TaulerDisplayerCallbacks cMethods)
    {
        $$$setupUI$$$();

        final JFrame frame = new JFrame("JugarPartida");
        frame.setContentPane(panel1);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        taulerDisplayer1.setTauler(taulerProgres);
        taulerDisplayer1.setCallbackMethods(cMethods);
        frame.pack();
        taulerDisplayer1.requestFocusInWindow();
        frame.setVisible(true);

        EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                frame.toFront();
                frame.repaint();
            }
        });

        guardarPartidaButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent actionEvent)
            {
                ControladorPartida.guardarPartida();
                System.out.println("Partida guardada correctament!");
            }
        });

        sortirButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent actionEvent)
            {
                ControladorHidato.descartaPartida();
                frame.dispose();
            }
        });
    }

    public void createUIComponents()
    {
        taulerDisplayer1 = new TaulerDisplayer();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(taulerDisplayer1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        guardarPartidaButton = new JButton();
        guardarPartidaButton.setText("Guardar Partida");
        panel1.add(guardarPartidaButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sortirButton = new JButton();
        sortirButton.setText("Sortir");
        panel1.add(sortirButton, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel1;
    }
}
