import javax.swing.*;
import java.awt.*;

/**
 * Created by daniel on 13/10/15.
 */
public class MenuPrincipal
{
    private JPanel panel1;
    private JLabel etiquetaNomUsuari;

    public MenuPrincipal()
    {
        JFrame frame = new JFrame("MenuPrincipal");
        $$$setupUI$$$();
        frame.setContentPane(panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        etiquetaNomUsuari.setText(CapaDomini.getUsuariActual().getNomUsuari());

        frame.pack();
        frame.setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        etiquetaNomUsuari = new JLabel();
        etiquetaNomUsuari.setText("Label");
        panel1.add(etiquetaNomUsuari, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel1;
    }
}
